/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 49e8bcf947cdd6e146a790e0d5f81ebd)
interface __BaseEnv_Env {
	CONTENT_BUCKET: R2Bucket;
	MANAGER_DB: D1Database;
	SITE_URL: "https://goldenone.arkalpooltech.workers.dev";
	PUBLIC_KEYSTATIC_GITHUB_REPO: "yiloveM/goldenone260727";
	PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: "goldenone260727";
	PUBLIC_R2_ASSET_BASE_URL: "https://goldenone.arkalpooltech.workers.dev/r2";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./node_modules/@astrojs/cloudflare/dist/entrypoints/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "PUBLIC_KEYSTATIC_GITHUB_REPO" | "PUBLIC_KEYSTATIC_GITHUB_APP_SLUG" | "PUBLIC_R2_ASSET_BASE_URL">> {}
}
