/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dd108b69ad93ad013332c57460c02833)
interface __BaseEnv_Env {
	CONTENT_BUCKET: R2Bucket;
	MANAGER_DB: D1Database;
	SITE_URL: "https://goldenone.arkalpooltech.workers.dev";
	PUBLIC_KEYSTATIC_GITHUB_REPO: "yiloveM/goldenone260727";
	KEYSTATIC_PORTAL_HOST: "admin.ebr.kdns.fr";
	MANAGER_PORTAL_HOST: "manager.ebr.kdns.fr";
	PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: "goldenone260727";
	PUBLIC_R2_ASSET_BASE_URL: "https://goldenone.arkalpooltech.workers.dev/r2";
	PUBLIC_R2_IMAGE_DELIVERY_MODE: "original";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "PUBLIC_KEYSTATIC_GITHUB_REPO" | "KEYSTATIC_PORTAL_HOST" | "MANAGER_PORTAL_HOST" | "PUBLIC_KEYSTATIC_GITHUB_APP_SLUG" | "PUBLIC_R2_ASSET_BASE_URL" | "PUBLIC_R2_IMAGE_DELIVERY_MODE">> {}
}
